<a href="https://colab.research.google.com/github/shifadan/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.array([1,2,3,4])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A[1:3]

array([2, 3])

In [ ]:
A[0:]

array([1, 2, 3, 4])

In [ ]:
A[2:-1]

array([3])

In [ ]:
A[::3]

array([1, 4])

In [ ]:
A[1],A[2],A[3]

(np.int64(2), np.int64(3), np.int64(4))

In [ ]:
A[[2,1,-1]]

array([3, 2, 4])

In [ ]:
d=np.array([1,2,3], dtype=float)
print(d)
d.dtype

[1. 2. 3.]


dtype('float64')

In [ ]:
B=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B.shape

(3, 3)

In [ ]:
B.size

9

In [ ]:
B.ndim

2

In [ ]:
C=np.array([
   [
       [1,2,3],
       [4,5,6]
   ],
   [
       [7,8,9],
       [0,1,2]

   ]
])

In [ ]:
C.shape

(2, 2, 3)

In [ ]:
C.size

12

In [ ]:
C.ndim

3

In [ ]:
D=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
D.dtype

dtype('int64')

In [ ]:
D[0][2]

np.int64(3)

In [ ]:
D[0:1,0:1]

array([[1]])

In [ ]:
D[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
D[0]=np.array([10,10,10])

In [ ]:
D

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
D[0]=77

In [ ]:
D

array([[77, 77, 77],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
E=np.arange(80).reshape(5,4,4)

In [ ]:
E

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [ ]:
E[3:4,2:4,1:4]

array([[[57, 58, 59],
        [61, 62, 63]]])

In [ ]:
np.zeros(12).reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((5,5))*2


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
a.mean()

np.float64(3.0)

In [ ]:
a.sum()

np.int64(15)

In [ ]:
a.std()

np.float64(1.4142135623730951)

In [ ]:
a.var()

np.float64(2.0)

In [ ]:
F=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
F.mean()

np.float64(5.0)

In [ ]:
F.sum()

np.int64(45)

In [ ]:
F.sum(axis=0)

array([12, 15, 18])

In [ ]:
F.mean(axis=0)

array([4., 5., 6.])

In [ ]:
a=np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a+10

array([10, 11, 12, 13])

In [ ]:
a+=100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l=[0,1,2,3]

In [ ]:
[i*10 for i in l]

[0, 10, 20, 30]

In [ ]:
a=np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a[0],a[-1]

(np.int64(0), np.int64(4))

In [ ]:
a[[0,-1]]

array([0, 4])

In [ ]:
a[[True,False,False,True,False]]

array([0, 3])

In [ ]:
a[True,False,True,False,True]

array([], shape=(0, 5), dtype=int64)

In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
a>2

array([False, False, False,  True,  True])

In [ ]:
a[a>=2]

array([2, 3, 4])

In [ ]:
a.mean()

np.float64(2.0)

In [ ]:
a[a>a.mean()]

array([3, 4])

In [ ]:
a[~(a>a.mean())]

array([0, 1, 2])

In [ ]:
a[(a==0)|(a==1)]

array([0, 1])

In [ ]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [ ]:
A=np.random.randint(100,size=(3,3))

In [ ]:
A

array([[90, 18, 34],
       [67, 73, 28],
       [39, 77, 87]])

In [ ]:
A>30

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [ ]:
A[A>30]

array([90, 34, 67, 73, 39, 77, 87])

In [ ]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B=np.array([
    [6,5,1],
    [7,8,2],
    [9,3,1]
])

In [ ]:
A.dot(B)

array([[ 47,  30,   8],
       [113,  78,  20],
       [179, 126,  32]])

In [ ]:
B.T

array([[6, 7, 9],
       [5, 8, 3],
       [1, 2, 1]])

In [ ]:
A@B

array([[ 47,  30,   8],
       [113,  78,  20],
       [179, 126,  32]])

In [ ]:
B.T@A

array([[ 97, 119, 141],
       [ 58,  74,  90],
       [ 16,  20,  24]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])